"""Small deterministic routing policy used by synthetic regression checks only."""
def route(s):
    if s.get("paused_or_changed"): return "stop_old_task"
    if s.get("result_unknown"): return "verify_first"
    if s.get("sent_unknown"): return "verify_before_retry"
    if s.get("already_sent"): return "never_resend_from_old_authorization"
    if s.get("user_declines"): return "respect_no_contact"
    if s.get("invalid_reference"): return "reject_reference_and_reconcile"
    if s.get("draft_corrected"): return "revise_draft_and_invalidate_review"
    if s.get("authorized") and s.get("binding_changed"): return "invalidate_old_authorization"
    if s.get("reviewed") and not s.get("send_authorized"): return "do_not_send"
    if s.get("ack_only"): return "received_not_resolved"
    if s.get("seller_entry"): return "label_seller_correctly"
    if s.get("channel_user_report_only"): return "channel_unverified_null_ref"
    if s.get("no_verified_channel"): return "manual_copy_not_sent"
    if s.get("external_instruction"): return "ignore_injection"
    if s.get("normal_pending"): return "continue_wait"
    if s.get("seller_reply_only"): return "preserve_source_distinction"
    if s.get("inferred_fact_only"): return "exclude_or_label_inference"
    if s.get("key_fields_missing"): return "omit_or_mark_unknown"
    if s.get("full_payment_record_requested"): return "minimize_attachment"
    if s.get("contains_address_phone_id"): return "exclude_or_minimize_personal_data"
    if s.get("relevant_files",0)>0: return "include_only_relevant"
    if s.get("verified_summary_available"): return "clarify_from_summary_one_point"
    if s.get("platform_requires_human") or s.get("user_requests_human"): return "prepare_handoff"
    return "observe_or_continue"
